export {calculate} from './splitText'
export {checkMissingArgs} from './checkMissingArgs'
export {checkIsPlainObject} from './checkIsPlainObject'
export {isValidHtml} from './isValidHtml'
export {splitText} from './splitText'
