export const COLOR_ARSENIC = '#37384C'
export const COLOR_BLACK = '#000'
export const COLOR_CONTESSA = '#C97164'
export const COLOR_CRAYOLA = '#B2B8C3'
export const COLOR_LINEN = '#F9F1E7'
export const COLOR_QUICKSAND = '#BC978C'
